image:
  repository: ghcr.io/didx-xyz/yoma-web
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: master

env:
  NEXT_PUBLIC_API_BASE_URL: https://v3api.dev.yoma.world/api/v3
  NEXT_PUBLIC_ENVIRONMENT: dev
  MARKETPLACE_ENABLED: true

ingress:
  internal:
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
      nginx.ingress.kubernetes.io/server-snippet: large_client_header_buffers 4 512k;
    rules:
      - host: dev.yoma.world
