name: yoma-v3
services:
  yoma-web:
    # platform: linux/amd64 # Until we get multi-arch docker images
    image: ${REGISTRY:-local}/yoma-web:${YOUTH_TAG:-latest}
    container_name: yoma-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # CLIENT VARIABLES
        - NEXT_PUBLIC_ENVIRONMENT=local
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      # SERVER VARIABLES
      NEXTAUTH_SECRET: VerySecretAndSecureNextAuthSecret # openssl rand -base64 32
      KEYCLOAK_CLIENT_ID: yoma-web
      KEYCLOAK_CLIENT_SECRET: superSecretYomaWebClientSecret
      NEXTAUTH_URL: http://localhost:3000
      API_BASE_URL: http://yoma-api:5000/api/v3
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/yoma
      NEXT_PUBLIC_KEYCLOAK_DEFAULT_PROVIDER: yoma-web
      NEXT_PUBLIC_API_BASE_URL: http://localhost:5000/api/v3
      NEXT_PUBLIC_ENVIRONMENT: local
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: secret
      NEXT_PUBLIC_GA_MEASUREMENT_ID: secret
      SENTRY_AUTH_TOKEN: secret
      MARKETPLACE_ENABLED: true
